import { ModelId, ModelInfo, QuickPrompt } from "./types";

export const MODELS: Record<ModelId, ModelInfo> = {
  "echogpt": {
    id: "echogpt",
    name: "EchoGPT",
    provider: "EchoGPT",
    description: "Default engine: Proprietary adaptive multi-model router that automatically orchestrates the best model for any query.",
    contextWindow: "Adaptive Context",
    tag: "Default Auto-Router",
    badgeVariant: "echogpt",
    accentColor: "#10B981",
    speed: "Dynamic (140+ t/s)",
    strengths: ["Dynamic model routing", "Zero-latency dispatch", "Unified memory graph"],
  },
  "deepseek-v4-pro": {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    description: "Next-gen open reasoning architecture with zero-shot theorem proving and autonomous code synthesis.",
    contextWindow: "256k tokens",
    tag: "Extreme Math & Logic",
    badgeVariant: "deepseek",
    accentColor: "#4F46E5",
    speed: "Ultra Fast (105 t/s)",
    strengths: ["Complex mathematics", "Symbolic logic", "Chain-of-thought"],
  },
  "qwen-3-8-plus": {
    id: "qwen-3-8-plus",
    name: "Qwen 3.8 Plus",
    provider: "Alibaba",
    description: "Advanced agentic reasoning engine fine-tuned for complex enterprise workflows and multilingual execution.",
    contextWindow: "128k tokens",
    tag: "Multilingual & Agentic Tools",
    badgeVariant: "qwen",
    accentColor: "#7C3AED",
    speed: "Fast (95 t/s)",
    strengths: ["Agentic tool calling", "Multilingual fluency", "Enterprise data"],
  },
  "kimi-3": {
    id: "kimi-3",
    name: "Kimi 3",
    provider: "Moonshot",
    description: "Breakthrough long-context architecture for recursive codebase indexing and comprehensive book analysis.",
    contextWindow: "5M tokens",
    tag: "5M Infinite Context",
    badgeVariant: "kimi",
    accentColor: "#0284C7",
    speed: "Fast (90 t/s)",
    strengths: ["5M token capacity", "Full repository search", "Deep document synthesis"],
  },
  "gemini-3-8-flash": {
    id: "gemini-3-8-flash",
    name: "Gemini 3.8 Flash",
    provider: "Google",
    description: "High-frequency multimodal model engineered for instant real-time vision, audio, and DOM interaction.",
    contextWindow: "2M tokens",
    tag: "Sub-30ms Multimodal Speed",
    badgeVariant: "google",
    accentColor: "#3B82F6",
    speed: "Instant (180 t/s)",
    strengths: ["Sub-30ms latency", "Live DOM vision", "High-frequency streaming"],
  },
  "gpt-5-6": {
    id: "gpt-5-6",
    name: "GPT-5.6",
    provider: "OpenAI",
    description: "Flagship cognitive model offering human-parity architectural design, world simulation, and cross-domain mastery.",
    contextWindow: "512k tokens",
    tag: "Autonomous Frontier Intelligence",
    badgeVariant: "openai",
    accentColor: "#10A37F",
    speed: "Very Fast (92 t/s)",
    strengths: ["Autonomous reasoning", "World modeling", "Complex systems"],
  },
  "opus-5-5": {
    id: "opus-5-5",
    name: "Opus 5.5",
    provider: "Anthropic",
    description: "Anthropic's pinnacle reasoning system with deep recursive reflection and uncompromising code rigor.",
    contextWindow: "1M tokens",
    tag: "Dense Thinking & Reflection",
    badgeVariant: "anthropic",
    accentColor: "#D97706",
    speed: "Deliberate Reasoning (88 t/s)",
    strengths: ["Recursive thinking", "Deep nuance", "Critical code verification"],
  },
  // Backward compatibility mappings
  "claude-3-7-sonnet": {
    id: "claude-3-7-sonnet",
    name: "Opus 5.5",
    provider: "Anthropic",
    description: "Anthropic's pinnacle reasoning system with deep recursive reflection and uncompromising code rigor.",
    contextWindow: "1M tokens",
    tag: "Dense Thinking & Reflection",
    badgeVariant: "anthropic",
    accentColor: "#D97706",
    speed: "Deliberate Reasoning (88 t/s)",
    strengths: ["Recursive thinking", "Deep nuance", "Critical code verification"],
  },
  "gpt-4-5": {
    id: "gpt-4-5",
    name: "GPT-5.6",
    provider: "OpenAI",
    description: "Flagship cognitive model offering human-parity architectural design, world simulation, and cross-domain mastery.",
    contextWindow: "512k tokens",
    tag: "Autonomous Frontier Intelligence",
    badgeVariant: "openai",
    accentColor: "#10A37F",
    speed: "Very Fast (92 t/s)",
    strengths: ["Autonomous reasoning", "World modeling", "Complex systems"],
  },
  "gemini-2-0-pro": {
    id: "gemini-2-0-pro",
    name: "Gemini 3.8 Flash",
    provider: "Google",
    description: "High-frequency multimodal model engineered for instant real-time vision, audio, and DOM interaction.",
    contextWindow: "2M tokens",
    tag: "Sub-30ms Multimodal Speed",
    badgeVariant: "google",
    accentColor: "#3B82F6",
    speed: "Instant (180 t/s)",
    strengths: ["Sub-30ms latency", "Live DOM vision", "High-frequency streaming"],
  },
  "deepseek-r1": {
    id: "deepseek-r1",
    name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    description: "Next-gen open reasoning architecture with zero-shot theorem proving and autonomous code synthesis.",
    contextWindow: "256k tokens",
    tag: "Extreme Math & Logic",
    badgeVariant: "deepseek",
    accentColor: "#4F46E5",
    speed: "Ultra Fast (105 t/s)",
    strengths: ["Complex mathematics", "Symbolic logic", "Chain-of-thought"],
  },
  "llama-3-3-70b": {
    id: "llama-3-3-70b",
    name: "Qwen 3.8 Plus",
    provider: "Alibaba",
    description: "Advanced agentic reasoning engine fine-tuned for complex enterprise workflows and multilingual execution.",
    contextWindow: "128k tokens",
    tag: "Multilingual & Agentic Tools",
    badgeVariant: "qwen",
    accentColor: "#7C3AED",
    speed: "Fast (95 t/s)",
    strengths: ["Agentic tool calling", "Multilingual fluency", "Enterprise data"],
  },
  "claude-3-5-sonnet": {
    id: "claude-3-5-sonnet",
    name: "Opus 5.5",
    provider: "Anthropic",
    description: "Anthropic's pinnacle reasoning system with deep recursive reflection and uncompromising code rigor.",
    contextWindow: "1M tokens",
    tag: "Dense Thinking & Reflection",
    badgeVariant: "anthropic",
    accentColor: "#D97706",
    speed: "Deliberate Reasoning (88 t/s)",
    strengths: ["Recursive thinking", "Deep nuance", "Critical code verification"],
  },
  "gpt-4o": {
    id: "gpt-4o",
    name: "GPT-5.6",
    provider: "OpenAI",
    description: "Flagship cognitive model offering human-parity architectural design, world simulation, and cross-domain mastery.",
    contextWindow: "512k tokens",
    tag: "Autonomous Frontier Intelligence",
    badgeVariant: "openai",
    accentColor: "#10A37F",
    speed: "Very Fast (92 t/s)",
    strengths: ["Autonomous reasoning", "World modeling", "Complex systems"],
  },
  "gemini-1-5-pro": {
    id: "gemini-1-5-pro",
    name: "Gemini 3.8 Flash",
    provider: "Google",
    description: "High-frequency multimodal model engineered for instant real-time vision, audio, and DOM interaction.",
    contextWindow: "2M tokens",
    tag: "Sub-30ms Multimodal Speed",
    badgeVariant: "google",
    accentColor: "#3B82F6",
    speed: "Instant (180 t/s)",
    strengths: ["Sub-30ms latency", "Live DOM vision", "High-frequency streaming"],
  },
  "llama-3-1-70b": {
    id: "llama-3-1-70b",
    name: "Qwen 3.8 Plus",
    provider: "Alibaba",
    description: "Advanced agentic reasoning engine fine-tuned for complex enterprise workflows and multilingual execution.",
    contextWindow: "128k tokens",
    tag: "Multilingual & Agentic Tools",
    badgeVariant: "qwen",
    accentColor: "#7C3AED",
    speed: "Fast (95 t/s)",
    strengths: ["Agentic tool calling", "Multilingual fluency", "Enterprise data"],
  },
};

export const MODELS_LIST: ModelInfo[] = [
  MODELS["echogpt"],
  MODELS["deepseek-v4-pro"],
  MODELS["qwen-3-8-plus"],
  MODELS["kimi-3"],
  MODELS["gemini-3-8-flash"],
  MODELS["gpt-5-6"],
  MODELS["opus-5-5"],
];

export const DEFAULT_MODEL_ID: ModelId = "echogpt";

export const QUICK_PROMPTS: QuickPrompt[] = [
  {
    id: "explain-code",
    title: "Explain Code",
    prompt: "Can you analyze this code, explain how it works step-by-step, and point out any potential edge cases?",
    category: "code",
    icon: "code",
  },
  {
    id: "summarize-key-points",
    title: "Summarize",
    prompt: "Provide a concise executive summary with the top 3 actionable takeaways and key risks.",
    category: "analysis",
    icon: "file-text",
  },
  {
    id: "refactor-clean",
    title: "Refactor Cleanly",
    prompt: "Refactor the following snippet following clean code principles, strict typing, and high performance.",
    category: "code",
    icon: "wrench",
  },
  {
    id: "write-tests",
    title: "Write Tests",
    prompt: "Write comprehensive unit and integration tests covering happy paths, edge cases, and failure scenarios.",
    category: "code",
    icon: "check-circle",
  },
];
